title: Benjamin Philpot
description: Portfolio | Economics & Environmental Science

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
